sudo: required
services:
  - docker
before_install:
  - docker build -t jossiemathews/docker-react -f Dockerfile.dev .

script:
  - docker run jossiemathews/docker-react npm run test -- --coverage

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env",
  bucket-name: "elasticbeanstalk-us-east-2-885750698421"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
